### ISSUE TITLE
Project should target .net standard

### ISSUE THREAD

**Issue by alexdow-hc** [mlhpdx/s3-upload-stream#5]
This is a really useful project, but it would be usable to a wider variety of projects if it targeted .net standard.

**Comment by mlhpdx** [comment]
Change has been made -- good suggestion.

**Comment by alexdow-hc** [comment]
@mlhpdx Thanks for merging that! Would it be possible to push a new release?

**Comment by mlhpdx** [comment]
@alexdow-hc yep, done (available on GitHub package source). Also available nuget.org shortly.
